/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.payroll.gui;

/**
 *
 * @author USER
 */
public class AddEmployeeDialog extends javax.swing.JDialog {
    public boolean isSaved = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddEmployeeDialog.class.getName());

    /**
     * Creates new form AddEmployeeDialog
     */
    public AddEmployeeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jBankAcc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSalary = new javax.swing.JTextField();
        jHBP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnAddEmployee1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add Employee");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 10, 340, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 740, 56);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full-Time Employee", "Hourly Contractor", "Commissioned Salesperson" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(250, 80, 270, 40);

        jLabel6.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel6.setText("Employee ID:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 140, 150, 30);

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel7.setText("Employee Type:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 90, 150, 30);
        jPanel1.add(jID);
        jID.setBounds(250, 140, 270, 30);

        jLabel8.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel8.setText("Full Name:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 180, 150, 30);

        jName.addActionListener(this::jNameActionPerformed);
        jPanel1.add(jName);
        jName.setBounds(250, 180, 270, 30);

        jLabel9.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel9.setText("Bank Account:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 220, 150, 30);
        jPanel1.add(jBankAcc);
        jBankAcc.setBounds(250, 220, 270, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel10.setText("Health Benefits Premium: ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 340, 170, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel11.setText("Monthly Salary:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 310, 120, 30);
        jPanel1.add(jSalary);
        jSalary.setBounds(300, 300, 180, 30);
        jPanel1.add(jHBP);
        jHBP.setBounds(300, 340, 180, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Payment Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 51, 102))); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 280, 480, 110);

        btnCancel.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(102, 102, 102));
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        jPanel1.add(btnCancel);
        btnCancel.setBounds(280, 450, 80, 20);

        btnAddEmployee1.setBackground(new java.awt.Color(102, 102, 102));
        btnAddEmployee1.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnAddEmployee1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddEmployee1.setText("+ Add Employee");
        btnAddEmployee1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddEmployee1.addActionListener(this::btnAddEmployee1ActionPerformed);
        jPanel1.add(btnAddEmployee1);
        btnAddEmployee1.setBounds(380, 440, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNameActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddEmployee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployee1ActionPerformed
        // TODO add your handling code here:
        if (getEmpName().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter an employee name.");
            return;
        }
    
    // 2. Set our flag to true so the main GUI knows we confirmed the save
        this.isSaved = true;
    
    // 3. Close the dialog
        this.dispose();
        
    }//GEN-LAST:event_btnAddEmployee1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AddEmployeeDialog dialog = new AddEmployeeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    public String getEmpType() {
        return jComboBox1.getSelectedItem().toString();
    }

    public String getEmpName() {
        return jName.getText().trim();
    }

    public String getBankAccount() {
        return jBankAcc.getText().trim();
    }

    public String getSalary() {
    return jSalary.getText().trim(); // Monthly Salary text field
    }

    public String getPremium() {
        return jHBP.getText().trim(); // Health Benefits Premium text field
    }
    public String getEmpID() {
    // Replace jTextField1 with your actual text field variable name for the ID
        return jID.getText().trim(); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JTextField jBankAcc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jHBP;
    private javax.swing.JTextField jID;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jSalary;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
