/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.payroll.gui;

/**
 *
 * @author USER
 */
public class MainPayrollGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainPayrollGUI.class.getName());
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> rowSorter;

    /**
     * Creates new form MainPayrollGUI
     */
    public MainPayrollGUI() {
        initComponents();
        initSearchAndEdit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEditSelected = new javax.swing.JButton();
        btnRemoveeEmployee = new javax.swing.JButton();
        btnAddEmployee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGenerateReport1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Automated Payroll System");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 340, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage your workplace and payroll calculations");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 60, 300, 14);

        jPanel1.setLayout(null);

        btnEditSelected.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnEditSelected.setText("Edit Selected");
        btnEditSelected.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEditSelected.addActionListener(this::btnEditSelectedActionPerformed);
        jPanel1.add(btnEditSelected);
        btnEditSelected.setBounds(360, 10, 160, 40);

        btnRemoveeEmployee.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnRemoveeEmployee.setText("Remove Selected");
        btnRemoveeEmployee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRemoveeEmployee.addActionListener(this::btnRemoveeEmployeeActionPerformed);
        jPanel1.add(btnRemoveeEmployee);
        btnRemoveeEmployee.setBounds(190, 10, 160, 40);

        btnAddEmployee.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnAddEmployee.setText("+ Add Employee");
        btnAddEmployee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddEmployee.addActionListener(this::btnAddEmployeeActionPerformed);
        jPanel1.add(btnAddEmployee);
        btnAddEmployee.setBounds(20, 10, 160, 40);

        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable2.setForeground(new java.awt.Color(153, 255, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Name", "Bank Account", "Type", "Net Pay"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 100, 660, 180);

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employees: 1");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 4, 110, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Company Payout:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(410, 0, 270, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 320, 660, 40);

        btnGenerateReport1.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        btnGenerateReport1.setText("Generate Report");
        btnGenerateReport1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGenerateReport1.addActionListener(this::btnGenerateReport1ActionPerformed);
        jPanel1.add(btnGenerateReport1);
        btnGenerateReport1.setBounds(530, 10, 160, 40);

        jLabel1.setText("🔍 Search:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 70, 70, 16);

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(90, 70, 490, 22);

        jButton1.setText("Clear");
        jPanel1.add(jButton1);
        jButton1.setBounds(600, 70, 72, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 95, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 356, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSelectedActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an employee row to edit.");
            return;
        }

        int modelRow = jTable2.convertRowIndexToModel(selectedRow);
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();

        String id   = model.getValueAt(modelRow, 0).toString();
        String name = model.getValueAt(modelRow, 1).toString();
        String bank = model.getValueAt(modelRow, 2).toString();
        String type = model.getValueAt(modelRow, 3).toString();

        AddEmployeeDialog editForm = new AddEmployeeDialog(this, true);
        editForm.setEmpID(id);
        editForm.setEmpType(type);
        editForm.setEmpName(name);
        editForm.setBankAccount(bank);
        editForm.setLocationRelativeTo(this);
        editForm.setVisible(true);

        if (editForm.isSaved) {
            String newName = editForm.getEmpName();
            String newBank = editForm.getBankAccount();
            String newType = editForm.getEmpType();

            double monthlySalary = 0.0;
            double healthPremium = 0.0;
            try {
                if (!editForm.getSalary().isEmpty()) {
                    monthlySalary = Double.parseDouble(editForm.getSalary());
                }
                if (!editForm.getPremium().isEmpty()) {
                    healthPremium = Double.parseDouble(editForm.getPremium());
                }
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers for Salary and Premiums.");
                return;
            }

            double netSalary = monthlySalary - healthPremium;
            String formattedNetPay = "$" + String.format("%.2f", netSalary);

            model.setValueAt(newName,         modelRow, 1);
            model.setValueAt(newBank,         modelRow, 2);
            model.setValueAt(newType,         modelRow, 3);
            model.setValueAt(formattedNetPay, modelRow, 4);

            updateTotalPayout();
        }
    }//GEN-LAST:event_btnEditSelectedActionPerformed

    private void btnRemoveeEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveeEmployeeActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
    
    // 2. Identify which row index is currently selected (-1 means nothing selected)
        int selectedRow = jTable2.getSelectedRow();
    
        if (selectedRow != -1) {
        // 3. Remove the row from the data model structure
            model.removeRow(selectedRow);
        
        // 4. (Optional) Call a helper method to recalculate total payout counters below
            updateTotalPayout();
        } else {
        // Warn the user if they clicked delete without selecting anyone
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an employee row to remove.");
        }
    }//GEN-LAST:event_btnRemoveeEmployeeActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
        AddEmployeeDialog addForm = new AddEmployeeDialog(this, true);
        addForm.setLocationRelativeTo(this);
    
    // The program pauses here until the user closes the dialog window
        addForm.setVisible(true);
    
    // 2. When execution resumes, check if they clicked "+ Add Employee" inside the form
        if (addForm.isSaved) {
        // Grab the exact Employee ID you typed into the form
            String empID = addForm.getEmpID(); 
        
        // Grab the rest of the text inputs from the dialog
            String type = addForm.getEmpType();
            String name = addForm.getEmpName();
            String bank = addForm.getBankAccount();
        
        // 3. Convert text strings into numbers and calculate Net Salary
            double monthlySalary = 0.0;
            double healthPremium = 0.0;
        
            try {
                if (!addForm.getSalary().isEmpty()) {
                    monthlySalary = Double.parseDouble(addForm.getSalary());
                }
                if (!addForm.getPremium().isEmpty()) {
                    healthPremium = Double.parseDouble(addForm.getPremium());
                }
            } catch (NumberFormatException e) {
            // Error handling if a user accidentally types letters/symbols instead of numbers
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter valid numbers for Salary and Premiums.");
                return;
            }
        
        // Perform the math: Monthly Salary minus Health Benefits Premium
            double netSalary = monthlySalary - healthPremium;
            String formattedNetPay = "$" + String.format("%.2f", netSalary);
        
        // 4. Grab the table model and push the data row into the grid
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
            model.addRow(new Object[]{empID, name, bank, type, formattedNetPay});
        
        // 5. Recalculate summary footer panels completely
            updateTotalPayout(); 
        }
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnGenerateReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReport1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerateReport1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // filtering is handled by the DocumentListener in initSearchAndEdit()
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void initSearchAndEdit() {
        // Wire TableRowSorter for real-time filtering
        rowSorter = new javax.swing.table.TableRowSorter<>(
                (javax.swing.table.DefaultTableModel) jTable2.getModel());
        jTable2.setRowSorter(rowSorter);

        // DocumentListener on jTextField1 — filters on every keystroke
        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e)  { applyFilter(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e)  { applyFilter(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { applyFilter(); }

            private void applyFilter() {
                String text = jTextField1.getText().trim();
                if (text.isEmpty()) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter(
                            "(?i)" + java.util.regex.Pattern.quote(text), 0, 1, 3));
                }
            }
        });

        // Wire Clear button (jButton1)
        jButton1.addActionListener(e -> jTextField1.setText(""));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainPayrollGUI().setVisible(true));
    }
    private void updateTotalPayout() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable2.getModel();
    double total = 0;
    
    // Loop through every single row inside the Net Pay column
    for (int i = 0; i < model.getRowCount(); i++) {
        // Assuming Net Pay is in column index 4
        Object value = model.getValueAt(i, 4);
        if (value != null) {
            // Strip out '$' or spacing characters before parsing numbers
            String strVal = value.toString().replace("$", "").trim();
            total += Double.parseDouble(strVal);
        }
    }
    
    // Update your summary labels dynamically
    jLabel6.setText("Employees: " + model.getRowCount());
    jLabel7.setText("Total Company Payout: $" + String.format("%.2f", total));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnEditSelected;
    private javax.swing.JButton btnGenerateReport1;
    private javax.swing.JButton btnRemoveeEmployee;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
